***Data Preparation***

In [67]:
import pandas as pd
import numpy as np
import sys

In [84]:
emp_df = pd.read_excel("employeDataProfile.xlsx", sheet_name="employee_comp", index_col="ID_EMP")
emp_df

,NAME,POSITION,LEVEL,GOOD_COMP,BAD_COMP
ID_EMP,,,,,
5367,Mansur,Worker,1,Problem Solving;Strategic Agility,Customer Focus;Drive for Result;Integrity & Tr...
5372,Abdullah Arif,Worker,1,Customer Focus;Sizing Up People;Strategic Agility,Drive for Result;Integrity & Trust;Interperson...
5415,Moh. Rofi'I,Worker,1,Customer Focus;Integrity & Trust;Interpersonal...,Drive for Result;Investigation Skill;Negotiati...
5416,Sayyimin,Worker,1,Strategic Agility,Customer Focus;Drive for Result;Integrity & Tr...
5417,Supriyanto,Worker,1,NaN,Customer Focus;Drive for Result;Integrity & Tr...
...,...,...,...,...,...
19189,Samuel Hasian Napitupulu,Staff,1,Customer Focus;Drive for Result;Integrity & Tr...,Analytical Thinking;Data Research;Insurance;Ri...
19291,Sasanti Suryabetari .,Team Leader,2,Change Management;Conflict Management;Continuo...,Asset Management;Communication Skill;Customer ...
19404,Robert Irawan,Staff,1,Analytical Thinking;Customer Focus;Data Resear...,Learning Agility;Strategic Agility
19426,Maria Gabriela Indrawati Niosie,Middle Manager,3,Asset Management;Conflict Management;Drive for...,Assessment Center;Behavioral Event Interview;B...
19479,Ananta Bagus Saputra,Staff,1,Customer Focus;Drive for Result;Integrity & Tr...,5R;Administration;Interpersonal Agility;K3;Qua...

In [85]:
training_df = pd.read_excel("employeDataProfile.xlsx", sheet_name="training_list", index_col="TRAIN_ID")
training_df

                                       COURSE_NAME        COMPETENCY  LEVEL
TRAIN_ID
1               5R : Improvement Management System                5R      3
2         5R : Strategy and Control for Managerial                5R      4
3                             5R Advanced Training                5R      3
4                         5R Intermediate Training                5R      2
5                                         Basic 5R                5R      1
...                                            ...               ...    ...
1026                      Wood Maintenance Methods  Wood Maintenance      2
1027               Advanced Business Communication     Writing Skill      4
1028                           Basic Writing Skill     Writing Skill      1
1029                       Corporate Communication     Writing Skill      3
1030                    Improve your Writing Skill     Writing Skill      2

[1030 rows x 3 columns]

In [78]:
def select_level(dataframe, level):
    selected_df = training_df[training_df["LEVEL"] == level]
    return selected_df

In [80]:
def are_similar(df1, df2):
    if df1.shape != df2.shape:
        return False
        
    if not df1.columns.equals(df2.columns):
        return False

    if not df1.equals(df2):
        return False

    return True

In [86]:
user_input = input("Enter employee name: ").title().strip()
if user_input not in emp_df['NAME'].values:
    print("not found")
    sys.exit()
else:
    emp = emp_df.loc[emp_df['NAME'] == user_input] #take row from dataframe
    comp = str(emp['BAD_COMP'].iloc[0])
    target_list = comp.split(";")
    lvl = int(emp['LEVEL'].iloc[0])
    selected_df = select_level(training_df, lvl)
    list_exist = selected_df['COMPETENCY'].apply(lambda x: any(item in x for item in target_list)).any()
    try:
        recommendation = []
        for item in target_list:
            try:
                training_id = selected_df.index[selected_df['COMPETENCY'] == item].tolist()[0]
                things = selected_df.loc[training_id, 'COURSE_NAME']
                recommendation.append(things)
            except IndexError as e:
                print("Error:", e)
                print("Index", item, "is out of range")
    except Exception as e:
        print("An error has occurred: ", e)
    num = 0
    for x in recommendation:
        num += 1
        print("{}. {}".format(num, x))

Enter employee name:  Dimas Luthfianto

1. Effective Asset Management
2. Business Improvement
3. Change Management Program - Start Your Change Journey Now
4. Advanced Basic Management
5. Continuous Process & Quality Improvement
6. Data Analysis for Business
7. Kaizen in the office - Team Level
8. Effective Planning & Organizing
9. Advanced Project Management
10. Effective Root Cause Analysis
11. Intermediate Shipping, Freight Forwarding and Logistic
12. Leadership by Character
13. Building Strategic Agility